auto:        true
server:      true


pygments:    true
permalink: /:categories/:title
baseurl: /eaternity-website
url: http://mklarmann.github.com
exclude: 
    Foundation
    CNAME
    README
    .gitignore
